// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/__dev/password-recovery/latest-preview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/__dev/password-recovery/latest-preview.get').default>>>>
    }
    '/api/admin/access-history/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/access-history/export.get').default>>>>
    }
    '/api/admin/access-history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/access-history/index.get').default>>>>
    }
    '/api/admin/marbete-templates/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/marbete-templates/[id].get').default>>>>
    }
    '/api/admin/marbete-templates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/marbete-templates/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/marbete-templates/index.post').default>>>>
    }
    '/api/admin/personas-autorizadas/access-action': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/access-action.post').default>>>>
    }
    '/api/admin/personas-autorizadas/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/config.post').default>>>>
    }
    '/api/admin/personas-autorizadas/marbete': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/marbete.get').default>>>>
    }
    '/api/admin/personas-autorizadas/pass-search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/pass-search.get').default>>>>
    }
    '/api/admin/personas-autorizadas/readiness': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/readiness.get').default>>>>
    }
    '/api/admin/personas-autorizadas/uploads': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/personas-autorizadas/uploads.post').default>>>>
    }
    '/api/admin/superadmin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/superadmin/users.get').default>>>>
    }
    '/api/auth/admin/google': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/admin/google.post').default>>>>
    }
    '/api/auth/admin/impersonate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/admin/impersonate.post').default>>>>
    }
    '/api/auth/admin/preview-daycare': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/admin/preview-daycare.post').default>>>>
    }
    '/api/auth/impersonation/exit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/impersonation/exit.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/password/change': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password/change.post').default>>>>
    }
    '/api/auth/password/forgot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password/forgot.post').default>>>>
    }
    '/api/auth/password/reset': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password/reset.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password/reset.post').default>>>>
    }
    '/api/daycare/admin/family-accounts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/family-accounts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/family-accounts.post').default>>>>
    }
    '/api/daycare/admin/resources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/resources.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/resources.post').default>>>>
    }
    '/api/daycare/admin/resources/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/resources/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/resources/[id].patch').default>>>>
    }
    '/api/daycare/admin/salas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/salas.get').default>>>>
    }
    '/api/daycare/admin/salas/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/salas/[id].get').default>>>>
    }
    '/api/daycare/admin/salas/:id/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/salas/[id]/overview.get').default>>>>
    }
    '/api/daycare/admin/salas/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/salas/overview.get').default>>>>
    }
    '/api/daycare/admin/uploads': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/admin/uploads.post').default>>>>
    }
    '/api/daycare/family/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/family/dashboard.get').default>>>>
    }
    '/api/daycare/family/resources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/family/resources.get').default>>>>
    }
    '/api/daycare/registration': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/registration.post').default>>>>
    }
    '/api/daycare/registration/captcha': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/registration/captcha.get').default>>>>
    }
    '/api/daycare/registration/options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daycare/registration/options.get').default>>>>
    }
    '/api/dev/husky-pass/options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dev/husky-pass/options.get').default>>>>
    }
    '/api/dev/husky-pass/pass': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dev/husky-pass/pass.get').default>>>>
    }
    '/api/dev/husky-pass/photo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dev/husky-pass/photo.get').default>>>>
    }
    '/api/family/attendance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/family/attendance/index.get').default>>>>
    }
    '/api/family/attendance/motivo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/family/attendance/motivo.post').default>>>>
    }
    '/api/personas-autorizadas/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/config.get').default>>>>
    }
    '/api/personas-autorizadas/credential': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/credential.get').default>>>>
    }
    '/api/personas-autorizadas/faces': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/faces.post').default>>>>
    }
    '/api/personas-autorizadas/family/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/family/[id].delete').default>>>>
    }
    '/api/personas-autorizadas/family': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/family/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/family/index.post').default>>>>
    }
    '/api/personas-autorizadas/marbete': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/marbete.get').default>>>>
    }
    '/api/personas-autorizadas/photo-source': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/photo-source.post').default>>>>
    }
    '/api/personas-autorizadas/scan': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/scan.get').default>>>>
    }
    '/api/personas-autorizadas/sibling-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/sibling-session.post').default>>>>
    }
    '/api/personas-autorizadas/student-photo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/student-photo.post').default>>>>
    }
    '/api/personas-autorizadas/student': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/student.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/personas-autorizadas/student.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}