export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptCalendly, useScriptLinkedInInsight, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAppSession } from '../composables/useAppSession';
export { useResolvedPersonasTheme, usePersonasFamilyTheme } from '../composables/usePersonasTheme';
export { normalizeAttendanceText, makeSchoolYearRange, parseSchoolYearLabel, currentSchoolYearStart, buildSchoolYearOptions, resolveSchoolYearOption, dateOnly, formatAttendanceDate, formatAttendanceTime } from '../utils/attendance';
export { dateInputValue, createAuthorizedPersonForm, validateAuthorizedPersonForm, authorizedPersonFormIsValid, toAuthorizedPersonSavePayload, AuthorizedPersonFormModel, AuthorizedPersonValidationState } from '../utils/authorizedPersonForm';
export { normalizeCurp, parseCurpBirthDate, calculateAgeFromIsoDate, CurpBirthDateResult } from '../utils/curp';
export { parseLegacyDate, formatDate, formatCalendarDay, isImageResource, isPdfResource, stripHtml, publishedPdfViewerUrl, normalizeVirtualAssetUrl, authorizedPersonLabel, appAbsoluteUrl, authorizedPersonValidationPath, authorizedPersonQrPath, authorizedPersonCredentialPath, authorizedPersonPrintPath, authorizedPersonMarbetePath, isHiddenResource, daycareResourceTypeLabel, daycareResourceSection } from '../utils/daycare';
export { normalizeExperienceName, normalizeInstitutionName, normalizeNivelIdentity, normalizePlantelIdentity, institutionFromContextData, defaultLoginRouteForExperience, recoveryRouteForExperience, defaultRouteForExperience, resolveExperienceContext, visualIdentityForContext, experienceThemeVars, resolveVisualIdentity, identityDiagnosticsPayload } from '../utils/experienceIdentity';
export { resolveGrupoIcon, GrupoIconManifestEntry, GrupoIconManifest, ResolvedGrupoIcon } from '../utils/grupoIcons';
export { normalizeMatricula, displayMatricula, isMatriculaLike, displayMatriculaCandidate, sameMatricula, matriculaSearchText } from '../utils/matricula';
export { PA_COLORS, PERSONAS_THEMES, normalizePlantel, normalizeNivel, personasThemeKeyFromMatricula, resolvePersonasTheme, personasThemeStyle, allPersonasThemes, personasMascot, personasLevelName, personasInstitutionName, personasInstitutionLogo, PersonasMascotVariant } from '../utils/personasTheme';
export { anonymousSession, useRouteSessionCache, setCachedRouteSession, getRouteSession } from '../utils/routeSession';
export { DAYCARE_FAMILY_ROLE, DAYCARE_ADMIN_ROLE, hasRoleToken, hasFamilyScope, hasDaycareAdminScope, defaultFamilyRoute, familyNavItems } from '../utils/sessionScopes';
export { SUPER_ADMIN_EMAIL, normalizeEmail, isConfiguredSuperAdminEmail } from '../utils/superAdmin';
export { evaluateVisionFaceValidation, toVisionImageUrl, canProcessWithVision, markValidatedVisionPhotoUrl, isValidatedVisionPhotoUrl, getCachedProcessedFaceImage, processFaceImage, processFaceImageCached, VisionFaceResult, VisionFaceValidation } from '../utils/visionFace';